#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

profile:
  path: /profile
  controller: App\Controller\ProfileController::index

# show:
#   path: /profile/{slug}-{id}
#   controller: App\Controller\ProfileController::show
#   requirements: 
#     page: --> trouver comment faire le requirement

